substitutions:
  _KEY_NAME: "systera-api-env"

steps:
  - id: 'extract-env'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['kms', 'decrypt', '--plaintext-file=.env', '--ciphertext-file=.env.enc', '--location=global', '--keyring=cloudbuild-secret', '--key=$_KEY_NAME']

  - id: 'docker:build_and_push'
    waitFor: ['extract-env']
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
      - -c
      - docker build . -t gcr.io/startail-io/systera-api &&
        docker push gcr.io/startail-io/systera-api

  - id: 'maven:deploy'
    waitFor: ['extract-env']
    name: 'maven:3.6.0-jdk-8-slim'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        source .env
        mkdir -p $$HOME/.m2/
        echo -n "\$$CI_MVN_SETTINGS" > $$HOME/.m2/settings.xml
        ls $$HOME/.m2/
        bash ./systerapb/make-java.sh deploy
