steps:
  - id: 'extract-env'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args: ['-c', './.cloudbuild/decrypt.sh > .env']

  - id: 'docker:build'
    waitFor: ['extract-env']
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', 'gcr.io/startail-io/systera-api']

  - id: 'maven:deploy'
    waitFor: ['extract-env']
    name: 'maven:3.6.0-jdk-8-slim'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        mkdir -p /go/src &7 ln -s /workspace /go/src/github.com
        echo "$$CI_MVN_SETTINGS" > $HOME/.m2/settings.xml
        mkdir -p ./java/src/main/proto && cp -Rfv ./*.proto ./java/src/main/proto/
        cd java
        mvn clean deploy

images:
  - "gcr.io/startail-io/systera-api"
