// Code generated by protoc-gen-go. DO NOT EDIT.
// source: systera.proto

package systerapb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// PLAYER PUNISHMENTS
type PunishLevel int32

const (
	PunishLevel_WARN    PunishLevel = 0
	PunishLevel_KICK    PunishLevel = 1
	PunishLevel_TEMPBAN PunishLevel = 2
	PunishLevel_PERMBAN PunishLevel = 3
)

var PunishLevel_name = map[int32]string{
	0: "WARN",
	1: "KICK",
	2: "TEMPBAN",
	3: "PERMBAN",
}
var PunishLevel_value = map[string]int32{
	"WARN":    0,
	"KICK":    1,
	"TEMPBAN": 2,
	"PERMBAN": 3,
}

func (x PunishLevel) String() string {
	return proto.EnumName(PunishLevel_name, int32(x))
}
func (PunishLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{0}
}

type SystemStream_Type int32

const (
	SystemStream_DISPATCH SystemStream_Type = 0
	SystemStream_ANNOUNCE SystemStream_Type = 1
)

var SystemStream_Type_name = map[int32]string{
	0: "DISPATCH",
	1: "ANNOUNCE",
}
var SystemStream_Type_value = map[string]int32{
	"DISPATCH": 0,
	"ANNOUNCE": 1,
}

func (x SystemStream_Type) String() string {
	return proto.EnumName(SystemStream_Type_name, int32(x))
}
func (SystemStream_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{4, 0}
}

type PlayerEntryStream_Type int32

const (
	PlayerEntryStream_ALL      PlayerEntryStream_Type = 0
	PlayerEntryStream_GROUPS   PlayerEntryStream_Type = 1
	PlayerEntryStream_SETTINGS PlayerEntryStream_Type = 2
)

var PlayerEntryStream_Type_name = map[int32]string{
	0: "ALL",
	1: "GROUPS",
	2: "SETTINGS",
}
var PlayerEntryStream_Type_value = map[string]int32{
	"ALL":      0,
	"GROUPS":   1,
	"SETTINGS": 2,
}

func (x PlayerEntryStream_Type) String() string {
	return proto.EnumName(PlayerEntryStream_Type_name, int32(x))
}
func (PlayerEntryStream_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{5, 0}
}

type PunishEntryStream_Type int32

const (
	PunishEntryStream_PUNISH PunishEntryStream_Type = 0
)

var PunishEntryStream_Type_name = map[int32]string{
	0: "PUNISH",
}
var PunishEntryStream_Type_value = map[string]int32{
	"PUNISH": 0,
}

func (x PunishEntryStream_Type) String() string {
	return proto.EnumName(PunishEntryStream_Type_name, int32(x))
}
func (PunishEntryStream_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{6, 0}
}

type ReportEntryStream_Type int32

const (
	ReportEntryStream_REPORT ReportEntryStream_Type = 0
)

var ReportEntryStream_Type_name = map[int32]string{
	0: "REPORT",
}
var ReportEntryStream_Type_value = map[string]int32{
	"REPORT": 0,
}

func (x ReportEntryStream_Type) String() string {
	return proto.EnumName(ReportEntryStream_Type_name, int32(x))
}
func (ReportEntryStream_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{7, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PlayerData struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{1}
}
func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (dst *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(dst, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *PlayerData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//
// Stream API
type AnnounceRequest struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnounceRequest) Reset()         { *m = AnnounceRequest{} }
func (m *AnnounceRequest) String() string { return proto.CompactTextString(m) }
func (*AnnounceRequest) ProtoMessage()    {}
func (*AnnounceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{2}
}
func (m *AnnounceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnounceRequest.Unmarshal(m, b)
}
func (m *AnnounceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnounceRequest.Marshal(b, m, deterministic)
}
func (dst *AnnounceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnounceRequest.Merge(dst, src)
}
func (m *AnnounceRequest) XXX_Size() int {
	return xxx_messageInfo_AnnounceRequest.Size(m)
}
func (m *AnnounceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnounceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnnounceRequest proto.InternalMessageInfo

func (m *AnnounceRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *AnnounceRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DispatchRequest struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Cmd                  string   `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DispatchRequest) Reset()         { *m = DispatchRequest{} }
func (m *DispatchRequest) String() string { return proto.CompactTextString(m) }
func (*DispatchRequest) ProtoMessage()    {}
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{3}
}
func (m *DispatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DispatchRequest.Unmarshal(m, b)
}
func (m *DispatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DispatchRequest.Marshal(b, m, deterministic)
}
func (dst *DispatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DispatchRequest.Merge(dst, src)
}
func (m *DispatchRequest) XXX_Size() int {
	return xxx_messageInfo_DispatchRequest.Size(m)
}
func (m *DispatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DispatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DispatchRequest proto.InternalMessageInfo

func (m *DispatchRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *DispatchRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

// System
type SystemStream struct {
	Type                 SystemStream_Type `protobuf:"varint,1,opt,name=type,proto3,enum=systerapb.SystemStream_Type" json:"type,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SystemStream) Reset()         { *m = SystemStream{} }
func (m *SystemStream) String() string { return proto.CompactTextString(m) }
func (*SystemStream) ProtoMessage()    {}
func (*SystemStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{4}
}
func (m *SystemStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemStream.Unmarshal(m, b)
}
func (m *SystemStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemStream.Marshal(b, m, deterministic)
}
func (dst *SystemStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemStream.Merge(dst, src)
}
func (m *SystemStream) XXX_Size() int {
	return xxx_messageInfo_SystemStream.Size(m)
}
func (m *SystemStream) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemStream.DiscardUnknown(m)
}

var xxx_messageInfo_SystemStream proto.InternalMessageInfo

func (m *SystemStream) GetType() SystemStream_Type {
	if m != nil {
		return m.Type
	}
	return SystemStream_DISPATCH
}

func (m *SystemStream) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// Player
type PlayerEntryStream struct {
	Type                 PlayerEntryStream_Type `protobuf:"varint,1,opt,name=type,proto3,enum=systerapb.PlayerEntryStream_Type" json:"type,omitempty"`
	Entry                *PlayerEntry           `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PlayerEntryStream) Reset()         { *m = PlayerEntryStream{} }
func (m *PlayerEntryStream) String() string { return proto.CompactTextString(m) }
func (*PlayerEntryStream) ProtoMessage()    {}
func (*PlayerEntryStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{5}
}
func (m *PlayerEntryStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerEntryStream.Unmarshal(m, b)
}
func (m *PlayerEntryStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerEntryStream.Marshal(b, m, deterministic)
}
func (dst *PlayerEntryStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerEntryStream.Merge(dst, src)
}
func (m *PlayerEntryStream) XXX_Size() int {
	return xxx_messageInfo_PlayerEntryStream.Size(m)
}
func (m *PlayerEntryStream) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerEntryStream.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerEntryStream proto.InternalMessageInfo

func (m *PlayerEntryStream) GetType() PlayerEntryStream_Type {
	if m != nil {
		return m.Type
	}
	return PlayerEntryStream_ALL
}

func (m *PlayerEntryStream) GetEntry() *PlayerEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

// Punishment
type PunishEntryStream struct {
	Type                 PunishEntryStream_Type `protobuf:"varint,1,opt,name=type,proto3,enum=systerapb.PunishEntryStream_Type" json:"type,omitempty"`
	Entry                *PunishEntry           `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PunishEntryStream) Reset()         { *m = PunishEntryStream{} }
func (m *PunishEntryStream) String() string { return proto.CompactTextString(m) }
func (*PunishEntryStream) ProtoMessage()    {}
func (*PunishEntryStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{6}
}
func (m *PunishEntryStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PunishEntryStream.Unmarshal(m, b)
}
func (m *PunishEntryStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PunishEntryStream.Marshal(b, m, deterministic)
}
func (dst *PunishEntryStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PunishEntryStream.Merge(dst, src)
}
func (m *PunishEntryStream) XXX_Size() int {
	return xxx_messageInfo_PunishEntryStream.Size(m)
}
func (m *PunishEntryStream) XXX_DiscardUnknown() {
	xxx_messageInfo_PunishEntryStream.DiscardUnknown(m)
}

var xxx_messageInfo_PunishEntryStream proto.InternalMessageInfo

func (m *PunishEntryStream) GetType() PunishEntryStream_Type {
	if m != nil {
		return m.Type
	}
	return PunishEntryStream_PUNISH
}

func (m *PunishEntryStream) GetEntry() *PunishEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

// Report
type ReportEntryStream struct {
	Type                 ReportEntryStream_Type `protobuf:"varint,1,opt,name=type,proto3,enum=systerapb.ReportEntryStream_Type" json:"type,omitempty"`
	Entry                *ReportEntry           `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ReportEntryStream) Reset()         { *m = ReportEntryStream{} }
func (m *ReportEntryStream) String() string { return proto.CompactTextString(m) }
func (*ReportEntryStream) ProtoMessage()    {}
func (*ReportEntryStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{7}
}
func (m *ReportEntryStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportEntryStream.Unmarshal(m, b)
}
func (m *ReportEntryStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportEntryStream.Marshal(b, m, deterministic)
}
func (dst *ReportEntryStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportEntryStream.Merge(dst, src)
}
func (m *ReportEntryStream) XXX_Size() int {
	return xxx_messageInfo_ReportEntryStream.Size(m)
}
func (m *ReportEntryStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportEntryStream.DiscardUnknown(m)
}

var xxx_messageInfo_ReportEntryStream proto.InternalMessageInfo

func (m *ReportEntryStream) GetType() ReportEntryStream_Type {
	if m != nil {
		return m.Type
	}
	return ReportEntryStream_REPORT
}

func (m *ReportEntryStream) GetEntry() *ReportEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

//
// PLAYER PROFILE
type PlayerEntry struct {
	PlayerUUID           string          `protobuf:"bytes,1,opt,name=playerUUID,proto3" json:"playerUUID,omitempty"`
	PlayerName           string          `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
	Groups               []string        `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Settings             map[string]bool `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PlayerEntry) Reset()         { *m = PlayerEntry{} }
func (m *PlayerEntry) String() string { return proto.CompactTextString(m) }
func (*PlayerEntry) ProtoMessage()    {}
func (*PlayerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{8}
}
func (m *PlayerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerEntry.Unmarshal(m, b)
}
func (m *PlayerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerEntry.Marshal(b, m, deterministic)
}
func (dst *PlayerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerEntry.Merge(dst, src)
}
func (m *PlayerEntry) XXX_Size() int {
	return xxx_messageInfo_PlayerEntry.Size(m)
}
func (m *PlayerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerEntry proto.InternalMessageInfo

func (m *PlayerEntry) GetPlayerUUID() string {
	if m != nil {
		return m.PlayerUUID
	}
	return ""
}

func (m *PlayerEntry) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *PlayerEntry) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *PlayerEntry) GetSettings() map[string]bool {
	if m != nil {
		return m.Settings
	}
	return nil
}

type InitPlayerProfileRequest struct {
	PlayerUUID           string   `protobuf:"bytes,1,opt,name=playerUUID,proto3" json:"playerUUID,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
	PlayerIPAddress      string   `protobuf:"bytes,3,opt,name=playerIPAddress,proto3" json:"playerIPAddress,omitempty"`
	PlayerHostname       string   `protobuf:"bytes,4,opt,name=playerHostname,proto3" json:"playerHostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitPlayerProfileRequest) Reset()         { *m = InitPlayerProfileRequest{} }
func (m *InitPlayerProfileRequest) String() string { return proto.CompactTextString(m) }
func (*InitPlayerProfileRequest) ProtoMessage()    {}
func (*InitPlayerProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{9}
}
func (m *InitPlayerProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitPlayerProfileRequest.Unmarshal(m, b)
}
func (m *InitPlayerProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitPlayerProfileRequest.Marshal(b, m, deterministic)
}
func (dst *InitPlayerProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitPlayerProfileRequest.Merge(dst, src)
}
func (m *InitPlayerProfileRequest) XXX_Size() int {
	return xxx_messageInfo_InitPlayerProfileRequest.Size(m)
}
func (m *InitPlayerProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitPlayerProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitPlayerProfileRequest proto.InternalMessageInfo

func (m *InitPlayerProfileRequest) GetPlayerUUID() string {
	if m != nil {
		return m.PlayerUUID
	}
	return ""
}

func (m *InitPlayerProfileRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *InitPlayerProfileRequest) GetPlayerIPAddress() string {
	if m != nil {
		return m.PlayerIPAddress
	}
	return ""
}

func (m *InitPlayerProfileRequest) GetPlayerHostname() string {
	if m != nil {
		return m.PlayerHostname
	}
	return ""
}

type InitPlayerProfileResponse struct {
	HasProfile           bool     `protobuf:"varint,1,opt,name=hasProfile,proto3" json:"hasProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitPlayerProfileResponse) Reset()         { *m = InitPlayerProfileResponse{} }
func (m *InitPlayerProfileResponse) String() string { return proto.CompactTextString(m) }
func (*InitPlayerProfileResponse) ProtoMessage()    {}
func (*InitPlayerProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{10}
}
func (m *InitPlayerProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitPlayerProfileResponse.Unmarshal(m, b)
}
func (m *InitPlayerProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitPlayerProfileResponse.Marshal(b, m, deterministic)
}
func (dst *InitPlayerProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitPlayerProfileResponse.Merge(dst, src)
}
func (m *InitPlayerProfileResponse) XXX_Size() int {
	return xxx_messageInfo_InitPlayerProfileResponse.Size(m)
}
func (m *InitPlayerProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitPlayerProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitPlayerProfileResponse proto.InternalMessageInfo

func (m *InitPlayerProfileResponse) GetHasProfile() bool {
	if m != nil {
		return m.HasProfile
	}
	return false
}

type FetchPlayerProfileRequest struct {
	PlayerUUID           string   `protobuf:"bytes,1,opt,name=playerUUID,proto3" json:"playerUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchPlayerProfileRequest) Reset()         { *m = FetchPlayerProfileRequest{} }
func (m *FetchPlayerProfileRequest) String() string { return proto.CompactTextString(m) }
func (*FetchPlayerProfileRequest) ProtoMessage()    {}
func (*FetchPlayerProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{11}
}
func (m *FetchPlayerProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchPlayerProfileRequest.Unmarshal(m, b)
}
func (m *FetchPlayerProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchPlayerProfileRequest.Marshal(b, m, deterministic)
}
func (dst *FetchPlayerProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchPlayerProfileRequest.Merge(dst, src)
}
func (m *FetchPlayerProfileRequest) XXX_Size() int {
	return xxx_messageInfo_FetchPlayerProfileRequest.Size(m)
}
func (m *FetchPlayerProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchPlayerProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchPlayerProfileRequest proto.InternalMessageInfo

func (m *FetchPlayerProfileRequest) GetPlayerUUID() string {
	if m != nil {
		return m.PlayerUUID
	}
	return ""
}

type FetchPlayerProfileByNameRequest struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=playerName,proto3" json:"playerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchPlayerProfileByNameRequest) Reset()         { *m = FetchPlayerProfileByNameRequest{} }
func (m *FetchPlayerProfileByNameRequest) String() string { return proto.CompactTextString(m) }
func (*FetchPlayerProfileByNameRequest) ProtoMessage()    {}
func (*FetchPlayerProfileByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{12}
}
func (m *FetchPlayerProfileByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchPlayerProfileByNameRequest.Unmarshal(m, b)
}
func (m *FetchPlayerProfileByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchPlayerProfileByNameRequest.Marshal(b, m, deterministic)
}
func (dst *FetchPlayerProfileByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchPlayerProfileByNameRequest.Merge(dst, src)
}
func (m *FetchPlayerProfileByNameRequest) XXX_Size() int {
	return xxx_messageInfo_FetchPlayerProfileByNameRequest.Size(m)
}
func (m *FetchPlayerProfileByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchPlayerProfileByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchPlayerProfileByNameRequest proto.InternalMessageInfo

func (m *FetchPlayerProfileByNameRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type FetchPlayerProfileResponse struct {
	Entry                *PlayerEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FetchPlayerProfileResponse) Reset()         { *m = FetchPlayerProfileResponse{} }
func (m *FetchPlayerProfileResponse) String() string { return proto.CompactTextString(m) }
func (*FetchPlayerProfileResponse) ProtoMessage()    {}
func (*FetchPlayerProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{13}
}
func (m *FetchPlayerProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchPlayerProfileResponse.Unmarshal(m, b)
}
func (m *FetchPlayerProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchPlayerProfileResponse.Marshal(b, m, deterministic)
}
func (dst *FetchPlayerProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchPlayerProfileResponse.Merge(dst, src)
}
func (m *FetchPlayerProfileResponse) XXX_Size() int {
	return xxx_messageInfo_FetchPlayerProfileResponse.Size(m)
}
func (m *FetchPlayerProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchPlayerProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchPlayerProfileResponse proto.InternalMessageInfo

func (m *FetchPlayerProfileResponse) GetEntry() *PlayerEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type SetPlayerGroupsRequest struct {
	PlayerUUID           string   `protobuf:"bytes,1,opt,name=playerUUID,proto3" json:"playerUUID,omitempty"`
	Groups               []string `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPlayerGroupsRequest) Reset()         { *m = SetPlayerGroupsRequest{} }
func (m *SetPlayerGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*SetPlayerGroupsRequest) ProtoMessage()    {}
func (*SetPlayerGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{14}
}
func (m *SetPlayerGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPlayerGroupsRequest.Unmarshal(m, b)
}
func (m *SetPlayerGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPlayerGroupsRequest.Marshal(b, m, deterministic)
}
func (dst *SetPlayerGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPlayerGroupsRequest.Merge(dst, src)
}
func (m *SetPlayerGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_SetPlayerGroupsRequest.Size(m)
}
func (m *SetPlayerGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPlayerGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPlayerGroupsRequest proto.InternalMessageInfo

func (m *SetPlayerGroupsRequest) GetPlayerUUID() string {
	if m != nil {
		return m.PlayerUUID
	}
	return ""
}

func (m *SetPlayerGroupsRequest) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

type SetPlayerServerRequest struct {
	PlayerUUID           string   `protobuf:"bytes,1,opt,name=playerUUID,proto3" json:"playerUUID,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=serverName,proto3" json:"serverName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPlayerServerRequest) Reset()         { *m = SetPlayerServerRequest{} }
func (m *SetPlayerServerRequest) String() string { return proto.CompactTextString(m) }
func (*SetPlayerServerRequest) ProtoMessage()    {}
func (*SetPlayerServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{15}
}
func (m *SetPlayerServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPlayerServerRequest.Unmarshal(m, b)
}
func (m *SetPlayerServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPlayerServerRequest.Marshal(b, m, deterministic)
}
func (dst *SetPlayerServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPlayerServerRequest.Merge(dst, src)
}
func (m *SetPlayerServerRequest) XXX_Size() int {
	return xxx_messageInfo_SetPlayerServerRequest.Size(m)
}
func (m *SetPlayerServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPlayerServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPlayerServerRequest proto.InternalMessageInfo

func (m *SetPlayerServerRequest) GetPlayerUUID() string {
	if m != nil {
		return m.PlayerUUID
	}
	return ""
}

func (m *SetPlayerServerRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type RemovePlayerServerRequest struct {
	PlayerUUID           string   `protobuf:"bytes,1,opt,name=playerUUID,proto3" json:"playerUUID,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=serverName,proto3" json:"serverName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePlayerServerRequest) Reset()         { *m = RemovePlayerServerRequest{} }
func (m *RemovePlayerServerRequest) String() string { return proto.CompactTextString(m) }
func (*RemovePlayerServerRequest) ProtoMessage()    {}
func (*RemovePlayerServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{16}
}
func (m *RemovePlayerServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePlayerServerRequest.Unmarshal(m, b)
}
func (m *RemovePlayerServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePlayerServerRequest.Marshal(b, m, deterministic)
}
func (dst *RemovePlayerServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePlayerServerRequest.Merge(dst, src)
}
func (m *RemovePlayerServerRequest) XXX_Size() int {
	return xxx_messageInfo_RemovePlayerServerRequest.Size(m)
}
func (m *RemovePlayerServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePlayerServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePlayerServerRequest proto.InternalMessageInfo

func (m *RemovePlayerServerRequest) GetPlayerUUID() string {
	if m != nil {
		return m.PlayerUUID
	}
	return ""
}

func (m *RemovePlayerServerRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type SetPlayerSettingsRequest struct {
	PlayerUUID           string   `protobuf:"bytes,1,opt,name=playerUUID,proto3" json:"playerUUID,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                bool     `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPlayerSettingsRequest) Reset()         { *m = SetPlayerSettingsRequest{} }
func (m *SetPlayerSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*SetPlayerSettingsRequest) ProtoMessage()    {}
func (*SetPlayerSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{17}
}
func (m *SetPlayerSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPlayerSettingsRequest.Unmarshal(m, b)
}
func (m *SetPlayerSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPlayerSettingsRequest.Marshal(b, m, deterministic)
}
func (dst *SetPlayerSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPlayerSettingsRequest.Merge(dst, src)
}
func (m *SetPlayerSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_SetPlayerSettingsRequest.Size(m)
}
func (m *SetPlayerSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPlayerSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPlayerSettingsRequest proto.InternalMessageInfo

func (m *SetPlayerSettingsRequest) GetPlayerUUID() string {
	if m != nil {
		return m.PlayerUUID
	}
	return ""
}

func (m *SetPlayerSettingsRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetPlayerSettingsRequest) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type PunishEntry struct {
	Available            bool        `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Level                PunishLevel `protobuf:"varint,2,opt,name=level,proto3,enum=systerapb.PunishLevel" json:"level,omitempty"`
	Reason               string      `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Date                 int64       `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Expire               int64       `protobuf:"varint,5,opt,name=expire,proto3" json:"expire,omitempty"`
	PunishedFrom         *PlayerData `protobuf:"bytes,6,opt,name=punishedFrom,proto3" json:"punishedFrom,omitempty"`
	PunishedTo           *PlayerData `protobuf:"bytes,7,opt,name=punishedTo,proto3" json:"punishedTo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PunishEntry) Reset()         { *m = PunishEntry{} }
func (m *PunishEntry) String() string { return proto.CompactTextString(m) }
func (*PunishEntry) ProtoMessage()    {}
func (*PunishEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{18}
}
func (m *PunishEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PunishEntry.Unmarshal(m, b)
}
func (m *PunishEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PunishEntry.Marshal(b, m, deterministic)
}
func (dst *PunishEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PunishEntry.Merge(dst, src)
}
func (m *PunishEntry) XXX_Size() int {
	return xxx_messageInfo_PunishEntry.Size(m)
}
func (m *PunishEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PunishEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PunishEntry proto.InternalMessageInfo

func (m *PunishEntry) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *PunishEntry) GetLevel() PunishLevel {
	if m != nil {
		return m.Level
	}
	return PunishLevel_WARN
}

func (m *PunishEntry) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *PunishEntry) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *PunishEntry) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *PunishEntry) GetPunishedFrom() *PlayerData {
	if m != nil {
		return m.PunishedFrom
	}
	return nil
}

func (m *PunishEntry) GetPunishedTo() *PlayerData {
	if m != nil {
		return m.PunishedTo
	}
	return nil
}

type GetPlayerPunishRequest struct {
	PlayerUUID           string      `protobuf:"bytes,1,opt,name=playerUUID,proto3" json:"playerUUID,omitempty"`
	FilterLevel          PunishLevel `protobuf:"varint,2,opt,name=filterLevel,proto3,enum=systerapb.PunishLevel" json:"filterLevel,omitempty"`
	IncludeExpired       bool        `protobuf:"varint,3,opt,name=includeExpired,proto3" json:"includeExpired,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPlayerPunishRequest) Reset()         { *m = GetPlayerPunishRequest{} }
func (m *GetPlayerPunishRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerPunishRequest) ProtoMessage()    {}
func (*GetPlayerPunishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{19}
}
func (m *GetPlayerPunishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerPunishRequest.Unmarshal(m, b)
}
func (m *GetPlayerPunishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerPunishRequest.Marshal(b, m, deterministic)
}
func (dst *GetPlayerPunishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerPunishRequest.Merge(dst, src)
}
func (m *GetPlayerPunishRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerPunishRequest.Size(m)
}
func (m *GetPlayerPunishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerPunishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerPunishRequest proto.InternalMessageInfo

func (m *GetPlayerPunishRequest) GetPlayerUUID() string {
	if m != nil {
		return m.PlayerUUID
	}
	return ""
}

func (m *GetPlayerPunishRequest) GetFilterLevel() PunishLevel {
	if m != nil {
		return m.FilterLevel
	}
	return PunishLevel_WARN
}

func (m *GetPlayerPunishRequest) GetIncludeExpired() bool {
	if m != nil {
		return m.IncludeExpired
	}
	return false
}

type GetPlayerPunishResponse struct {
	Entry                []*PunishEntry `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetPlayerPunishResponse) Reset()         { *m = GetPlayerPunishResponse{} }
func (m *GetPlayerPunishResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlayerPunishResponse) ProtoMessage()    {}
func (*GetPlayerPunishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{20}
}
func (m *GetPlayerPunishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerPunishResponse.Unmarshal(m, b)
}
func (m *GetPlayerPunishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerPunishResponse.Marshal(b, m, deterministic)
}
func (dst *GetPlayerPunishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerPunishResponse.Merge(dst, src)
}
func (m *GetPlayerPunishResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlayerPunishResponse.Size(m)
}
func (m *GetPlayerPunishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerPunishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerPunishResponse proto.InternalMessageInfo

func (m *GetPlayerPunishResponse) GetEntry() []*PunishEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type SetPlayerPunishRequest struct {
	Force                bool         `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	Entry                *PunishEntry `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetPlayerPunishRequest) Reset()         { *m = SetPlayerPunishRequest{} }
func (m *SetPlayerPunishRequest) String() string { return proto.CompactTextString(m) }
func (*SetPlayerPunishRequest) ProtoMessage()    {}
func (*SetPlayerPunishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{21}
}
func (m *SetPlayerPunishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPlayerPunishRequest.Unmarshal(m, b)
}
func (m *SetPlayerPunishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPlayerPunishRequest.Marshal(b, m, deterministic)
}
func (dst *SetPlayerPunishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPlayerPunishRequest.Merge(dst, src)
}
func (m *SetPlayerPunishRequest) XXX_Size() int {
	return xxx_messageInfo_SetPlayerPunishRequest.Size(m)
}
func (m *SetPlayerPunishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPlayerPunishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPlayerPunishRequest proto.InternalMessageInfo

func (m *SetPlayerPunishRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *SetPlayerPunishRequest) GetEntry() *PunishEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type SetPlayerPunishResponse struct {
	Noprofile            bool     `protobuf:"varint,1,opt,name=noprofile,proto3" json:"noprofile,omitempty"`
	Offline              bool     `protobuf:"varint,2,opt,name=offline,proto3" json:"offline,omitempty"`
	Duplicate            bool     `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	Cooldown             bool     `protobuf:"varint,4,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPlayerPunishResponse) Reset()         { *m = SetPlayerPunishResponse{} }
func (m *SetPlayerPunishResponse) String() string { return proto.CompactTextString(m) }
func (*SetPlayerPunishResponse) ProtoMessage()    {}
func (*SetPlayerPunishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{22}
}
func (m *SetPlayerPunishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPlayerPunishResponse.Unmarshal(m, b)
}
func (m *SetPlayerPunishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPlayerPunishResponse.Marshal(b, m, deterministic)
}
func (dst *SetPlayerPunishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPlayerPunishResponse.Merge(dst, src)
}
func (m *SetPlayerPunishResponse) XXX_Size() int {
	return xxx_messageInfo_SetPlayerPunishResponse.Size(m)
}
func (m *SetPlayerPunishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPlayerPunishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPlayerPunishResponse proto.InternalMessageInfo

func (m *SetPlayerPunishResponse) GetNoprofile() bool {
	if m != nil {
		return m.Noprofile
	}
	return false
}

func (m *SetPlayerPunishResponse) GetOffline() bool {
	if m != nil {
		return m.Offline
	}
	return false
}

func (m *SetPlayerPunishResponse) GetDuplicate() bool {
	if m != nil {
		return m.Duplicate
	}
	return false
}

func (m *SetPlayerPunishResponse) GetCooldown() bool {
	if m != nil {
		return m.Cooldown
	}
	return false
}

type ReportEntry struct {
	From                 *PlayerData `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *PlayerData `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Message              string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Date                 int64       `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Server               string      `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReportEntry) Reset()         { *m = ReportEntry{} }
func (m *ReportEntry) String() string { return proto.CompactTextString(m) }
func (*ReportEntry) ProtoMessage()    {}
func (*ReportEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{23}
}
func (m *ReportEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportEntry.Unmarshal(m, b)
}
func (m *ReportEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportEntry.Marshal(b, m, deterministic)
}
func (dst *ReportEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportEntry.Merge(dst, src)
}
func (m *ReportEntry) XXX_Size() int {
	return xxx_messageInfo_ReportEntry.Size(m)
}
func (m *ReportEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ReportEntry proto.InternalMessageInfo

func (m *ReportEntry) GetFrom() *PlayerData {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ReportEntry) GetTo() *PlayerData {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *ReportEntry) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReportEntry) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *ReportEntry) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type ReportRequest struct {
	From                 *PlayerData `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *PlayerData `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Message              string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{24}
}
func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (dst *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(dst, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetFrom() *PlayerData {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ReportRequest) GetTo() *PlayerData {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *ReportRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReportResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportResponse) Reset()         { *m = ReportResponse{} }
func (m *ReportResponse) String() string { return proto.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()    {}
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{25}
}
func (m *ReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResponse.Unmarshal(m, b)
}
func (m *ReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResponse.Marshal(b, m, deterministic)
}
func (dst *ReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResponse.Merge(dst, src)
}
func (m *ReportResponse) XXX_Size() int {
	return xxx_messageInfo_ReportResponse.Size(m)
}
func (m *ReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResponse proto.InternalMessageInfo

//
// GROUP PERMISISONS
type GroupEntry struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	GroupPrefix          string   `protobuf:"bytes,2,opt,name=groupPrefix,proto3" json:"groupPrefix,omitempty"`
	GlobalPerms          []string `protobuf:"bytes,3,rep,name=globalPerms,proto3" json:"globalPerms,omitempty"`
	ServerPerms          []string `protobuf:"bytes,4,rep,name=serverPerms,proto3" json:"serverPerms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupEntry) Reset()         { *m = GroupEntry{} }
func (m *GroupEntry) String() string { return proto.CompactTextString(m) }
func (*GroupEntry) ProtoMessage()    {}
func (*GroupEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{26}
}
func (m *GroupEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupEntry.Unmarshal(m, b)
}
func (m *GroupEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupEntry.Marshal(b, m, deterministic)
}
func (dst *GroupEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupEntry.Merge(dst, src)
}
func (m *GroupEntry) XXX_Size() int {
	return xxx_messageInfo_GroupEntry.Size(m)
}
func (m *GroupEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupEntry.DiscardUnknown(m)
}

var xxx_messageInfo_GroupEntry proto.InternalMessageInfo

func (m *GroupEntry) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *GroupEntry) GetGroupPrefix() string {
	if m != nil {
		return m.GroupPrefix
	}
	return ""
}

func (m *GroupEntry) GetGlobalPerms() []string {
	if m != nil {
		return m.GlobalPerms
	}
	return nil
}

func (m *GroupEntry) GetServerPerms() []string {
	if m != nil {
		return m.ServerPerms
	}
	return nil
}

type PermissionEntry struct {
	ServerName           string   `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Permissions          []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionEntry) Reset()         { *m = PermissionEntry{} }
func (m *PermissionEntry) String() string { return proto.CompactTextString(m) }
func (*PermissionEntry) ProtoMessage()    {}
func (*PermissionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{27}
}
func (m *PermissionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionEntry.Unmarshal(m, b)
}
func (m *PermissionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionEntry.Marshal(b, m, deterministic)
}
func (dst *PermissionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionEntry.Merge(dst, src)
}
func (m *PermissionEntry) XXX_Size() int {
	return xxx_messageInfo_PermissionEntry.Size(m)
}
func (m *PermissionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionEntry proto.InternalMessageInfo

func (m *PermissionEntry) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *PermissionEntry) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type FetchGroupsRequest struct {
	ServerName           string   `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchGroupsRequest) Reset()         { *m = FetchGroupsRequest{} }
func (m *FetchGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*FetchGroupsRequest) ProtoMessage()    {}
func (*FetchGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{28}
}
func (m *FetchGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchGroupsRequest.Unmarshal(m, b)
}
func (m *FetchGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchGroupsRequest.Marshal(b, m, deterministic)
}
func (dst *FetchGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchGroupsRequest.Merge(dst, src)
}
func (m *FetchGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_FetchGroupsRequest.Size(m)
}
func (m *FetchGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchGroupsRequest proto.InternalMessageInfo

func (m *FetchGroupsRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type FetchGroupsResponse struct {
	Groups               []*GroupEntry `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FetchGroupsResponse) Reset()         { *m = FetchGroupsResponse{} }
func (m *FetchGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*FetchGroupsResponse) ProtoMessage()    {}
func (*FetchGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{29}
}
func (m *FetchGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchGroupsResponse.Unmarshal(m, b)
}
func (m *FetchGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchGroupsResponse.Marshal(b, m, deterministic)
}
func (dst *FetchGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchGroupsResponse.Merge(dst, src)
}
func (m *FetchGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_FetchGroupsResponse.Size(m)
}
func (m *FetchGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchGroupsResponse proto.InternalMessageInfo

func (m *FetchGroupsResponse) GetGroups() []*GroupEntry {
	if m != nil {
		return m.Groups
	}
	return nil
}

type CreateGroupRequest struct {
	GroupName            string             `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	GroupPrefix          string             `protobuf:"bytes,2,opt,name=groupPrefix,proto3" json:"groupPrefix,omitempty"`
	PermsEntry           []*PermissionEntry `protobuf:"bytes,3,rep,name=permsEntry,proto3" json:"permsEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{30}
}
func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (dst *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(dst, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *CreateGroupRequest) GetGroupPrefix() string {
	if m != nil {
		return m.GroupPrefix
	}
	return ""
}

func (m *CreateGroupRequest) GetPermsEntry() []*PermissionEntry {
	if m != nil {
		return m.PermsEntry
	}
	return nil
}

type RemoveGroupRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveGroupRequest) Reset()         { *m = RemoveGroupRequest{} }
func (m *RemoveGroupRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveGroupRequest) ProtoMessage()    {}
func (*RemoveGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{31}
}
func (m *RemoveGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveGroupRequest.Unmarshal(m, b)
}
func (m *RemoveGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveGroupRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveGroupRequest.Merge(dst, src)
}
func (m *RemoveGroupRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveGroupRequest.Size(m)
}
func (m *RemoveGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveGroupRequest proto.InternalMessageInfo

func (m *RemoveGroupRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type AddPermissionRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Permissions          []string `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPermissionRequest) Reset()         { *m = AddPermissionRequest{} }
func (m *AddPermissionRequest) String() string { return proto.CompactTextString(m) }
func (*AddPermissionRequest) ProtoMessage()    {}
func (*AddPermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{32}
}
func (m *AddPermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPermissionRequest.Unmarshal(m, b)
}
func (m *AddPermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPermissionRequest.Marshal(b, m, deterministic)
}
func (dst *AddPermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPermissionRequest.Merge(dst, src)
}
func (m *AddPermissionRequest) XXX_Size() int {
	return xxx_messageInfo_AddPermissionRequest.Size(m)
}
func (m *AddPermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPermissionRequest proto.InternalMessageInfo

func (m *AddPermissionRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *AddPermissionRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *AddPermissionRequest) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type RemovePermissionRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Permissions          []string `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePermissionRequest) Reset()         { *m = RemovePermissionRequest{} }
func (m *RemovePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*RemovePermissionRequest) ProtoMessage()    {}
func (*RemovePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_systera_ee9793ed878b81a4, []int{33}
}
func (m *RemovePermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePermissionRequest.Unmarshal(m, b)
}
func (m *RemovePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePermissionRequest.Marshal(b, m, deterministic)
}
func (dst *RemovePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePermissionRequest.Merge(dst, src)
}
func (m *RemovePermissionRequest) XXX_Size() int {
	return xxx_messageInfo_RemovePermissionRequest.Size(m)
}
func (m *RemovePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePermissionRequest proto.InternalMessageInfo

func (m *RemovePermissionRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *RemovePermissionRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *RemovePermissionRequest) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "systerapb.Empty")
	proto.RegisterType((*PlayerData)(nil), "systerapb.PlayerData")
	proto.RegisterType((*AnnounceRequest)(nil), "systerapb.AnnounceRequest")
	proto.RegisterType((*DispatchRequest)(nil), "systerapb.DispatchRequest")
	proto.RegisterType((*SystemStream)(nil), "systerapb.SystemStream")
	proto.RegisterType((*PlayerEntryStream)(nil), "systerapb.PlayerEntryStream")
	proto.RegisterType((*PunishEntryStream)(nil), "systerapb.PunishEntryStream")
	proto.RegisterType((*ReportEntryStream)(nil), "systerapb.ReportEntryStream")
	proto.RegisterType((*PlayerEntry)(nil), "systerapb.PlayerEntry")
	proto.RegisterMapType((map[string]bool)(nil), "systerapb.PlayerEntry.SettingsEntry")
	proto.RegisterType((*InitPlayerProfileRequest)(nil), "systerapb.InitPlayerProfileRequest")
	proto.RegisterType((*InitPlayerProfileResponse)(nil), "systerapb.InitPlayerProfileResponse")
	proto.RegisterType((*FetchPlayerProfileRequest)(nil), "systerapb.FetchPlayerProfileRequest")
	proto.RegisterType((*FetchPlayerProfileByNameRequest)(nil), "systerapb.FetchPlayerProfileByNameRequest")
	proto.RegisterType((*FetchPlayerProfileResponse)(nil), "systerapb.FetchPlayerProfileResponse")
	proto.RegisterType((*SetPlayerGroupsRequest)(nil), "systerapb.SetPlayerGroupsRequest")
	proto.RegisterType((*SetPlayerServerRequest)(nil), "systerapb.SetPlayerServerRequest")
	proto.RegisterType((*RemovePlayerServerRequest)(nil), "systerapb.RemovePlayerServerRequest")
	proto.RegisterType((*SetPlayerSettingsRequest)(nil), "systerapb.SetPlayerSettingsRequest")
	proto.RegisterType((*PunishEntry)(nil), "systerapb.PunishEntry")
	proto.RegisterType((*GetPlayerPunishRequest)(nil), "systerapb.GetPlayerPunishRequest")
	proto.RegisterType((*GetPlayerPunishResponse)(nil), "systerapb.GetPlayerPunishResponse")
	proto.RegisterType((*SetPlayerPunishRequest)(nil), "systerapb.SetPlayerPunishRequest")
	proto.RegisterType((*SetPlayerPunishResponse)(nil), "systerapb.SetPlayerPunishResponse")
	proto.RegisterType((*ReportEntry)(nil), "systerapb.ReportEntry")
	proto.RegisterType((*ReportRequest)(nil), "systerapb.ReportRequest")
	proto.RegisterType((*ReportResponse)(nil), "systerapb.ReportResponse")
	proto.RegisterType((*GroupEntry)(nil), "systerapb.GroupEntry")
	proto.RegisterType((*PermissionEntry)(nil), "systerapb.PermissionEntry")
	proto.RegisterType((*FetchGroupsRequest)(nil), "systerapb.FetchGroupsRequest")
	proto.RegisterType((*FetchGroupsResponse)(nil), "systerapb.FetchGroupsResponse")
	proto.RegisterType((*CreateGroupRequest)(nil), "systerapb.CreateGroupRequest")
	proto.RegisterType((*RemoveGroupRequest)(nil), "systerapb.RemoveGroupRequest")
	proto.RegisterType((*AddPermissionRequest)(nil), "systerapb.AddPermissionRequest")
	proto.RegisterType((*RemovePermissionRequest)(nil), "systerapb.RemovePermissionRequest")
	proto.RegisterEnum("systerapb.PunishLevel", PunishLevel_name, PunishLevel_value)
	proto.RegisterEnum("systerapb.SystemStream_Type", SystemStream_Type_name, SystemStream_Type_value)
	proto.RegisterEnum("systerapb.PlayerEntryStream_Type", PlayerEntryStream_Type_name, PlayerEntryStream_Type_value)
	proto.RegisterEnum("systerapb.PunishEntryStream_Type", PunishEntryStream_Type_name, PunishEntryStream_Type_value)
	proto.RegisterEnum("systerapb.ReportEntryStream_Type", ReportEntryStream_Type_name, ReportEntryStream_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SysteraClient is the client API for Systera service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SysteraClient interface {
	Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*Empty, error)
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*Empty, error)
	InitPlayerProfile(ctx context.Context, in *InitPlayerProfileRequest, opts ...grpc.CallOption) (*InitPlayerProfileResponse, error)
	FetchPlayerProfile(ctx context.Context, in *FetchPlayerProfileRequest, opts ...grpc.CallOption) (*FetchPlayerProfileResponse, error)
	FetchPlayerProfileByName(ctx context.Context, in *FetchPlayerProfileByNameRequest, opts ...grpc.CallOption) (*FetchPlayerProfileResponse, error)
	SetPlayerGroups(ctx context.Context, in *SetPlayerGroupsRequest, opts ...grpc.CallOption) (*Empty, error)
	SetPlayerServer(ctx context.Context, in *SetPlayerServerRequest, opts ...grpc.CallOption) (*Empty, error)
	RemovePlayerServer(ctx context.Context, in *RemovePlayerServerRequest, opts ...grpc.CallOption) (*Empty, error)
	SetPlayerSettings(ctx context.Context, in *SetPlayerSettingsRequest, opts ...grpc.CallOption) (*Empty, error)
	GetPlayerPunish(ctx context.Context, in *GetPlayerPunishRequest, opts ...grpc.CallOption) (*GetPlayerPunishResponse, error)
	SetPlayerPunish(ctx context.Context, in *SetPlayerPunishRequest, opts ...grpc.CallOption) (*SetPlayerPunishResponse, error)
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	FetchGroups(ctx context.Context, in *FetchGroupsRequest, opts ...grpc.CallOption) (*FetchGroupsResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveGroup(ctx context.Context, in *RemoveGroupRequest, opts ...grpc.CallOption) (*Empty, error)
	AddPermission(ctx context.Context, in *AddPermissionRequest, opts ...grpc.CallOption) (*Empty, error)
	RemovePermission(ctx context.Context, in *RemovePermissionRequest, opts ...grpc.CallOption) (*Empty, error)
}

type systeraClient struct {
	cc *grpc.ClientConn
}

func NewSysteraClient(cc *grpc.ClientConn) SysteraClient {
	return &systeraClient{cc}
}

func (c *systeraClient) Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/Announce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/Dispatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) InitPlayerProfile(ctx context.Context, in *InitPlayerProfileRequest, opts ...grpc.CallOption) (*InitPlayerProfileResponse, error) {
	out := new(InitPlayerProfileResponse)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/InitPlayerProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) FetchPlayerProfile(ctx context.Context, in *FetchPlayerProfileRequest, opts ...grpc.CallOption) (*FetchPlayerProfileResponse, error) {
	out := new(FetchPlayerProfileResponse)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/FetchPlayerProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) FetchPlayerProfileByName(ctx context.Context, in *FetchPlayerProfileByNameRequest, opts ...grpc.CallOption) (*FetchPlayerProfileResponse, error) {
	out := new(FetchPlayerProfileResponse)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/FetchPlayerProfileByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) SetPlayerGroups(ctx context.Context, in *SetPlayerGroupsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/SetPlayerGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) SetPlayerServer(ctx context.Context, in *SetPlayerServerRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/SetPlayerServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) RemovePlayerServer(ctx context.Context, in *RemovePlayerServerRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/RemovePlayerServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) SetPlayerSettings(ctx context.Context, in *SetPlayerSettingsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/SetPlayerSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) GetPlayerPunish(ctx context.Context, in *GetPlayerPunishRequest, opts ...grpc.CallOption) (*GetPlayerPunishResponse, error) {
	out := new(GetPlayerPunishResponse)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/GetPlayerPunish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) SetPlayerPunish(ctx context.Context, in *SetPlayerPunishRequest, opts ...grpc.CallOption) (*SetPlayerPunishResponse, error) {
	out := new(SetPlayerPunishResponse)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/SetPlayerPunish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) FetchGroups(ctx context.Context, in *FetchGroupsRequest, opts ...grpc.CallOption) (*FetchGroupsResponse, error) {
	out := new(FetchGroupsResponse)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/FetchGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) RemoveGroup(ctx context.Context, in *RemoveGroupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/RemoveGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) AddPermission(ctx context.Context, in *AddPermissionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/AddPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systeraClient) RemovePermission(ctx context.Context, in *RemovePermissionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/systerapb.Systera/RemovePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysteraServer is the server API for Systera service.
type SysteraServer interface {
	Announce(context.Context, *AnnounceRequest) (*Empty, error)
	Dispatch(context.Context, *DispatchRequest) (*Empty, error)
	InitPlayerProfile(context.Context, *InitPlayerProfileRequest) (*InitPlayerProfileResponse, error)
	FetchPlayerProfile(context.Context, *FetchPlayerProfileRequest) (*FetchPlayerProfileResponse, error)
	FetchPlayerProfileByName(context.Context, *FetchPlayerProfileByNameRequest) (*FetchPlayerProfileResponse, error)
	SetPlayerGroups(context.Context, *SetPlayerGroupsRequest) (*Empty, error)
	SetPlayerServer(context.Context, *SetPlayerServerRequest) (*Empty, error)
	RemovePlayerServer(context.Context, *RemovePlayerServerRequest) (*Empty, error)
	SetPlayerSettings(context.Context, *SetPlayerSettingsRequest) (*Empty, error)
	GetPlayerPunish(context.Context, *GetPlayerPunishRequest) (*GetPlayerPunishResponse, error)
	SetPlayerPunish(context.Context, *SetPlayerPunishRequest) (*SetPlayerPunishResponse, error)
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	FetchGroups(context.Context, *FetchGroupsRequest) (*FetchGroupsResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*Empty, error)
	RemoveGroup(context.Context, *RemoveGroupRequest) (*Empty, error)
	AddPermission(context.Context, *AddPermissionRequest) (*Empty, error)
	RemovePermission(context.Context, *RemovePermissionRequest) (*Empty, error)
}

func RegisterSysteraServer(s *grpc.Server, srv SysteraServer) {
	s.RegisterService(&_Systera_serviceDesc, srv)
}

func _Systera_Announce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).Announce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/Announce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).Announce(ctx, req.(*AnnounceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/Dispatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_InitPlayerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitPlayerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).InitPlayerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/InitPlayerProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).InitPlayerProfile(ctx, req.(*InitPlayerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_FetchPlayerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPlayerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).FetchPlayerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/FetchPlayerProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).FetchPlayerProfile(ctx, req.(*FetchPlayerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_FetchPlayerProfileByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPlayerProfileByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).FetchPlayerProfileByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/FetchPlayerProfileByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).FetchPlayerProfileByName(ctx, req.(*FetchPlayerProfileByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_SetPlayerGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlayerGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).SetPlayerGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/SetPlayerGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).SetPlayerGroups(ctx, req.(*SetPlayerGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_SetPlayerServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlayerServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).SetPlayerServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/SetPlayerServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).SetPlayerServer(ctx, req.(*SetPlayerServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_RemovePlayerServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePlayerServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).RemovePlayerServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/RemovePlayerServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).RemovePlayerServer(ctx, req.(*RemovePlayerServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_SetPlayerSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlayerSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).SetPlayerSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/SetPlayerSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).SetPlayerSettings(ctx, req.(*SetPlayerSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_GetPlayerPunish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerPunishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).GetPlayerPunish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/GetPlayerPunish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).GetPlayerPunish(ctx, req.(*GetPlayerPunishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_SetPlayerPunish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlayerPunishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).SetPlayerPunish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/SetPlayerPunish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).SetPlayerPunish(ctx, req.(*SetPlayerPunishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_FetchGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).FetchGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/FetchGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).FetchGroups(ctx, req.(*FetchGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_RemoveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).RemoveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/RemoveGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).RemoveGroup(ctx, req.(*RemoveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_AddPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).AddPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/AddPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).AddPermission(ctx, req.(*AddPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systera_RemovePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysteraServer).RemovePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systerapb.Systera/RemovePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysteraServer).RemovePermission(ctx, req.(*RemovePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Systera_serviceDesc = grpc.ServiceDesc{
	ServiceName: "systerapb.Systera",
	HandlerType: (*SysteraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Announce",
			Handler:    _Systera_Announce_Handler,
		},
		{
			MethodName: "Dispatch",
			Handler:    _Systera_Dispatch_Handler,
		},
		{
			MethodName: "InitPlayerProfile",
			Handler:    _Systera_InitPlayerProfile_Handler,
		},
		{
			MethodName: "FetchPlayerProfile",
			Handler:    _Systera_FetchPlayerProfile_Handler,
		},
		{
			MethodName: "FetchPlayerProfileByName",
			Handler:    _Systera_FetchPlayerProfileByName_Handler,
		},
		{
			MethodName: "SetPlayerGroups",
			Handler:    _Systera_SetPlayerGroups_Handler,
		},
		{
			MethodName: "SetPlayerServer",
			Handler:    _Systera_SetPlayerServer_Handler,
		},
		{
			MethodName: "RemovePlayerServer",
			Handler:    _Systera_RemovePlayerServer_Handler,
		},
		{
			MethodName: "SetPlayerSettings",
			Handler:    _Systera_SetPlayerSettings_Handler,
		},
		{
			MethodName: "GetPlayerPunish",
			Handler:    _Systera_GetPlayerPunish_Handler,
		},
		{
			MethodName: "SetPlayerPunish",
			Handler:    _Systera_SetPlayerPunish_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _Systera_Report_Handler,
		},
		{
			MethodName: "FetchGroups",
			Handler:    _Systera_FetchGroups_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Systera_CreateGroup_Handler,
		},
		{
			MethodName: "RemoveGroup",
			Handler:    _Systera_RemoveGroup_Handler,
		},
		{
			MethodName: "AddPermission",
			Handler:    _Systera_AddPermission_Handler,
		},
		{
			MethodName: "RemovePermission",
			Handler:    _Systera_RemovePermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "systera.proto",
}

func init() { proto.RegisterFile("systera.proto", fileDescriptor_systera_ee9793ed878b81a4) }

var fileDescriptor_systera_ee9793ed878b81a4 = []byte{
	// 1454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x5f, 0x73, 0xdb, 0x44,
	0x10, 0xb7, 0x6c, 0x27, 0x71, 0xd6, 0x4d, 0xa2, 0x1e, 0x25, 0x75, 0x3c, 0xa5, 0x0d, 0x47, 0xcb,
	0xb4, 0x1d, 0xf0, 0x30, 0xa1, 0x9d, 0x29, 0xcd, 0x03, 0x75, 0x12, 0x37, 0x75, 0x9b, 0xba, 0x1a,
	0xc9, 0x19, 0x98, 0xc2, 0x03, 0x8a, 0x7d, 0x4e, 0x34, 0xc8, 0x92, 0x2a, 0xc9, 0xa1, 0x1e, 0x3e,
	0x02, 0xcc, 0xd0, 0x67, 0x5e, 0x19, 0xde, 0xf8, 0x14, 0x7c, 0x16, 0x3e, 0x08, 0x73, 0x7f, 0x24,
	0x9f, 0xfe, 0xd8, 0x51, 0xe9, 0xd0, 0x37, 0xed, 0xde, 0xee, 0xef, 0xf6, 0xf6, 0xf6, 0xdf, 0x09,
	0xd6, 0x82, 0x69, 0x10, 0x12, 0xdf, 0x6c, 0x79, 0xbe, 0x1b, 0xba, 0x68, 0x55, 0x90, 0xde, 0x09,
	0x5e, 0x81, 0xa5, 0xce, 0xd8, 0x0b, 0xa7, 0xf8, 0x1e, 0x80, 0x66, 0x9b, 0x53, 0xe2, 0x1f, 0x98,
	0xa1, 0x89, 0x10, 0x54, 0x8f, 0x8f, 0xbb, 0x07, 0x0d, 0x65, 0x5b, 0xb9, 0xbd, 0xaa, 0xb3, 0x6f,
	0xca, 0x73, 0xcc, 0x31, 0x69, 0x94, 0x39, 0x8f, 0x7e, 0xe3, 0x7d, 0xd8, 0x68, 0x3b, 0x8e, 0x3b,
	0x71, 0x06, 0x44, 0x27, 0xaf, 0x26, 0x24, 0x08, 0xd1, 0x26, 0x2c, 0x87, 0xa6, 0x7f, 0x4a, 0x42,
	0xa1, 0x2c, 0x28, 0xd4, 0x80, 0x95, 0x31, 0x09, 0x02, 0xf3, 0x34, 0x42, 0x88, 0x48, 0xbc, 0x0b,
	0x1b, 0x07, 0x56, 0xe0, 0x99, 0xe1, 0xe0, 0xec, 0x22, 0x10, 0x15, 0x2a, 0x83, 0xf1, 0x50, 0x00,
	0xd0, 0x4f, 0x7c, 0x0e, 0x97, 0x0c, 0x7a, 0x9a, 0xb1, 0x11, 0xfa, 0xc4, 0x1c, 0xa3, 0x2f, 0xa0,
	0x1a, 0x4e, 0x3d, 0xc2, 0xf4, 0xd6, 0x77, 0xae, 0xb5, 0xe2, 0xa3, 0xb6, 0x64, 0xb1, 0x56, 0x7f,
	0xea, 0x11, 0x9d, 0x49, 0x52, 0xcc, 0x71, 0x70, 0x1a, 0x61, 0x8e, 0x83, 0x53, 0x8c, 0xa1, 0x4a,
	0xd7, 0xd1, 0x25, 0xa8, 0x1d, 0x74, 0x0d, 0xad, 0xdd, 0xdf, 0x7f, 0xa2, 0x96, 0x28, 0xd5, 0xee,
	0xf5, 0x5e, 0x1c, 0xf7, 0xf6, 0x3b, 0xaa, 0x82, 0xff, 0x50, 0xe0, 0x32, 0x77, 0x58, 0xc7, 0x09,
	0xfd, 0xa9, 0xd8, 0xfd, 0x7e, 0x62, 0xf7, 0x8f, 0xa5, 0xdd, 0x33, 0xb2, 0xb2, 0x09, 0x9f, 0xc1,
	0x12, 0xa1, 0x2b, 0xcc, 0x88, 0xfa, 0xce, 0x66, 0xbe, 0x9e, 0xce, 0x85, 0xf0, 0x1d, 0x61, 0xde,
	0x0a, 0x54, 0xda, 0x47, 0x47, 0x6a, 0x09, 0x01, 0x2c, 0x1f, 0xea, 0x2f, 0x8e, 0x35, 0x43, 0x55,
	0xa8, 0x95, 0x46, 0xa7, 0xdf, 0xef, 0xf6, 0x0e, 0x0d, 0xb5, 0x8c, 0x7f, 0xa5, 0x56, 0x4e, 0x1c,
	0x2b, 0x38, 0x2b, 0x68, 0x65, 0x5a, 0xb6, 0xa8, 0x95, 0x33, 0xbd, 0xc8, 0x4a, 0x24, 0xac, 0x04,
	0x58, 0xd6, 0x8e, 0x7b, 0x5d, 0xe3, 0x89, 0x5a, 0x62, 0xe6, 0xe8, 0xc4, 0x73, 0xfd, 0xb0, 0x98,
	0x39, 0x19, 0xd9, 0x82, 0xe6, 0x48, 0x7a, 0x39, 0xe6, 0xe8, 0x1d, 0xed, 0x85, 0xde, 0x57, 0x4b,
	0xf8, 0x1f, 0x05, 0xea, 0x92, 0x7f, 0xd1, 0x75, 0x00, 0x8f, 0x91, 0x52, 0xec, 0x4b, 0x9c, 0xd9,
	0x7a, 0x6f, 0x96, 0x07, 0x12, 0x87, 0x46, 0xed, 0xa9, 0xef, 0x4e, 0xbc, 0xa0, 0x51, 0xd9, 0xae,
	0xd0, 0xa8, 0xe5, 0x14, 0x7a, 0x04, 0xb5, 0x80, 0x84, 0xa1, 0xe5, 0x9c, 0x06, 0x8d, 0xea, 0x76,
	0xe5, 0x76, 0x7d, 0xe7, 0x66, 0xfe, 0x0d, 0xb7, 0x0c, 0x21, 0xc6, 0x4d, 0x8f, 0xb5, 0x9a, 0xbb,
	0xb0, 0x96, 0x58, 0xa2, 0x41, 0xfb, 0x23, 0x99, 0x0a, 0x1b, 0xe9, 0x27, 0xba, 0x02, 0x4b, 0xe7,
	0xa6, 0x3d, 0xe1, 0x76, 0xd5, 0x74, 0x4e, 0x3c, 0x2c, 0x3f, 0x50, 0xf0, 0x5f, 0x0a, 0x34, 0xba,
	0x8e, 0x15, 0xf2, 0x8d, 0x34, 0xdf, 0x1d, 0x59, 0x76, 0x9c, 0xae, 0xef, 0x7a, 0xe6, 0xdb, 0xb0,
	0xc1, 0xa9, 0xae, 0xd6, 0x1e, 0x0e, 0x7d, 0x12, 0xd0, 0xc3, 0x53, 0xa1, 0x34, 0x1b, 0x7d, 0x0a,
	0xeb, 0x9c, 0xf5, 0xc4, 0x0d, 0x42, 0x56, 0x49, 0xaa, 0x4c, 0x30, 0xc5, 0xc5, 0xbb, 0xb0, 0x95,
	0x63, 0x6d, 0xe0, 0xb9, 0x4e, 0x40, 0xa8, 0x39, 0x67, 0x66, 0x20, 0xb8, 0xcc, 0xdc, 0x9a, 0x2e,
	0x71, 0xa8, 0xf2, 0x63, 0x12, 0x0e, 0xce, 0xfe, 0xcb, 0x59, 0x71, 0x1b, 0x6e, 0x64, 0x95, 0xf7,
	0xa6, 0xf4, 0x9c, 0x19, 0x08, 0xe6, 0x0e, 0x25, 0xed, 0x0e, 0xfc, 0x14, 0x9a, 0x79, 0xfb, 0x0b,
	0xeb, 0xe3, 0x90, 0x55, 0x8a, 0xe4, 0xb9, 0x06, 0x9b, 0x06, 0x11, 0x7e, 0x38, 0x64, 0x91, 0x54,
	0xf4, 0xd2, 0x66, 0x81, 0x58, 0x96, 0x03, 0x11, 0x7f, 0x2b, 0x21, 0x1a, 0xc4, 0x3f, 0x27, 0xfe,
	0x5b, 0x84, 0x41, 0xc0, 0x14, 0xe4, 0x30, 0x98, 0x71, 0xf0, 0x77, 0xb0, 0xa5, 0x93, 0xb1, 0x7b,
	0x4e, 0xfe, 0x0f, 0xf0, 0x13, 0x68, 0x48, 0x66, 0xf3, 0x34, 0x28, 0x8a, 0x2d, 0x12, 0xa5, 0x9c,
	0x93, 0x28, 0x15, 0x29, 0x51, 0xf0, 0x6f, 0x65, 0xa8, 0x4b, 0x55, 0x0c, 0x5d, 0x83, 0x55, 0xf3,
	0xdc, 0xb4, 0x6c, 0xf3, 0x24, 0x8e, 0xb3, 0x19, 0x83, 0x5e, 0xa4, 0x4d, 0xce, 0x89, 0xcd, 0x70,
	0xd7, 0x73, 0x4a, 0xe1, 0x11, 0x5d, 0xd5, 0xb9, 0x10, 0xbd, 0x0e, 0x9f, 0x98, 0x81, 0xeb, 0x88,
	0xd4, 0x10, 0x14, 0xed, 0xa8, 0x43, 0x33, 0xe4, 0x79, 0x50, 0xd1, 0xd9, 0x37, 0x95, 0x25, 0xaf,
	0x3d, 0xcb, 0x27, 0x8d, 0x25, 0xc6, 0x15, 0x14, 0xfa, 0x0a, 0x2e, 0x79, 0x0c, 0x99, 0x0c, 0x1f,
	0xfb, 0xee, 0xb8, 0xb1, 0xcc, 0x22, 0xe8, 0xc3, 0x4c, 0x04, 0xd1, 0xf6, 0xad, 0x27, 0x44, 0xd1,
	0x7d, 0x80, 0x88, 0xee, 0xbb, 0x8d, 0x95, 0x45, 0x8a, 0x92, 0x20, 0xfe, 0x5d, 0x81, 0xcd, 0xc3,
	0xc8, 0xed, 0xfc, 0x54, 0x45, 0x9d, 0xfe, 0x00, 0xea, 0x23, 0xcb, 0x0e, 0x89, 0x7f, 0x54, 0xc0,
	0x49, 0xb2, 0x28, 0x2d, 0x12, 0x96, 0x33, 0xb0, 0x27, 0x43, 0xd2, 0x61, 0xe7, 0x1e, 0x8a, 0x5b,
	0x4a, 0x71, 0xf1, 0x21, 0x5c, 0xcd, 0xd8, 0x96, 0x4d, 0xb2, 0xca, 0xc5, 0x6d, 0xea, 0x7b, 0x29,
	0x25, 0x92, 0x87, 0xbc, 0x02, 0x4b, 0x23, 0xd7, 0x1f, 0x44, 0xb7, 0xcf, 0x89, 0xb7, 0x6c, 0x82,
	0xbf, 0x28, 0x70, 0xd5, 0x98, 0x63, 0xe7, 0x35, 0x58, 0x75, 0x5c, 0x2f, 0x51, 0xc9, 0x66, 0x0c,
	0x3a, 0x2e, 0xb9, 0xa3, 0x91, 0x6d, 0x39, 0x51, 0x41, 0x8f, 0x48, 0xaa, 0x37, 0x9c, 0x78, 0xb6,
	0x35, 0xa0, 0xa1, 0xc3, 0xbd, 0x33, 0x63, 0xa0, 0x26, 0xd4, 0x06, 0xae, 0x6b, 0x0f, 0xdd, 0x9f,
	0x1c, 0x16, 0x57, 0x35, 0x3d, 0xa6, 0xf1, 0x9f, 0x0a, 0xd4, 0xa5, 0xd6, 0x88, 0xee, 0x40, 0x75,
	0x44, 0x63, 0x49, 0x59, 0x14, 0x12, 0x4c, 0x04, 0xdd, 0x82, 0x72, 0xe8, 0x8a, 0x33, 0xcf, 0x11,
	0x2c, 0x87, 0xae, 0x3c, 0xe4, 0x55, 0x12, 0x43, 0xde, 0xbc, 0x58, 0xe7, 0x59, 0xce, 0x62, 0x7d,
	0x55, 0x17, 0x14, 0xfe, 0x19, 0xd6, 0xb8, 0x99, 0xd1, 0x55, 0xbc, 0x47, 0x43, 0xb1, 0x0a, 0xeb,
	0xd1, 0xe6, 0xfc, 0xa2, 0xf0, 0x1b, 0x05, 0x80, 0xd5, 0xdf, 0xb8, 0x32, 0xb0, 0x72, 0x2a, 0x75,
	0x80, 0x19, 0x03, 0x6d, 0x43, 0x9d, 0x11, 0x9a, 0x4f, 0x46, 0xd6, 0x6b, 0x51, 0x77, 0x64, 0x16,
	0x93, 0xb0, 0xdd, 0x13, 0xd3, 0xd6, 0x88, 0x3f, 0x8e, 0x46, 0x05, 0x99, 0x45, 0x25, 0xb8, 0x27,
	0xb8, 0x44, 0x95, 0x4b, 0x48, 0x2c, 0x6c, 0xc0, 0x06, 0xfd, 0xb0, 0x82, 0xc0, 0x72, 0x9d, 0x78,
	0x78, 0x91, 0x8a, 0xa8, 0x92, 0x2e, 0xa2, 0x14, 0xd4, 0x8b, 0x55, 0xa2, 0xc6, 0x20, 0xb3, 0xf0,
	0x3d, 0x40, 0xac, 0x77, 0x65, 0x7a, 0xcd, 0x22, 0x5c, 0x7c, 0x00, 0x1f, 0x24, 0xb4, 0x44, 0x74,
	0x7f, 0x1e, 0xb7, 0x20, 0x9e, 0x86, 0xf2, 0x5d, 0xcc, 0x9c, 0x19, 0x77, 0xa6, 0x37, 0x0a, 0xa0,
	0x7d, 0x9f, 0x98, 0x21, 0x61, 0x8b, 0xd1, 0xe6, 0xef, 0xea, 0xeb, 0x87, 0x00, 0xf4, 0x84, 0x7c,
	0x68, 0x62, 0xae, 0xae, 0xef, 0x34, 0xe5, 0xa8, 0x48, 0x3a, 0x51, 0x97, 0xa4, 0xf1, 0x0e, 0x20,
	0xde, 0xd2, 0x8a, 0x5b, 0x84, 0x1d, 0xb8, 0xd2, 0x1e, 0x0e, 0x67, 0xa8, 0xc5, 0xce, 0x31, 0x7b,
	0xed, 0x94, 0x13, 0xaf, 0x9d, 0xd4, 0x95, 0x55, 0xb2, 0x57, 0xf6, 0x0a, 0xae, 0x8a, 0xb6, 0xfb,
	0xbe, 0xb6, 0xbc, 0xbb, 0x1b, 0xf5, 0x49, 0x5e, 0xb0, 0x6b, 0x50, 0xfd, 0xa6, 0xad, 0xf7, 0xd4,
	0x12, 0xfd, 0x7a, 0xd6, 0xdd, 0x7f, 0xa6, 0x2a, 0xa8, 0x0e, 0x2b, 0xfd, 0xce, 0x73, 0x6d, 0xaf,
	0xdd, 0x53, 0xcb, 0x94, 0xd0, 0x3a, 0xfa, 0x73, 0x4a, 0x54, 0x76, 0xfe, 0x06, 0x58, 0x31, 0xb8,
	0xf7, 0xd1, 0x43, 0xa8, 0x45, 0x6f, 0x47, 0x24, 0xdf, 0x49, 0xea, 0x41, 0xd9, 0x54, 0xa5, 0x35,
	0xfe, 0x56, 0x2d, 0x51, 0xdd, 0xe8, 0xc9, 0x98, 0xd0, 0x4d, 0xbd, 0x23, 0x73, 0x75, 0x7f, 0x80,
	0xcb, 0x99, 0xf9, 0x12, 0x7d, 0x22, 0x09, 0xce, 0x9b, 0x95, 0x9b, 0x37, 0x17, 0x0b, 0x89, 0x72,
	0x51, 0x42, 0x03, 0x91, 0x48, 0xc9, 0x2d, 0x64, 0xed, 0xb9, 0x33, 0x6a, 0xf3, 0xd6, 0x05, 0x52,
	0xf1, 0x26, 0x2e, 0x34, 0xe6, 0x0d, 0xab, 0xe8, 0xee, 0x42, 0x90, 0xc4, 0x44, 0x5b, 0x7c, 0xc3,
	0xc7, 0xb0, 0x91, 0x1a, 0x47, 0x91, 0xfc, 0x56, 0xcb, 0x1f, 0x55, 0xb3, 0x37, 0x90, 0xc0, 0xe1,
	0x73, 0x62, 0x3e, 0x4e, 0x62, 0x86, 0xcc, 0xc1, 0x39, 0x8a, 0xf2, 0x33, 0x01, 0x75, 0x33, 0xf1,
	0x0c, 0x9c, 0x33, 0x91, 0xe6, 0xa0, 0x3d, 0x85, 0xcb, 0x99, 0x19, 0x33, 0x11, 0x15, 0xf3, 0x26,
	0xd0, 0x1c, 0xac, 0x97, 0xb0, 0x91, 0x1a, 0x4e, 0x12, 0x27, 0xcc, 0x1f, 0xaa, 0x9a, 0x78, 0x91,
	0x48, 0x7c, 0x0b, 0x2f, 0x25, 0xef, 0xe5, 0x60, 0x1b, 0x17, 0x63, 0x1b, 0x73, 0xb1, 0xbf, 0x86,
	0x65, 0xde, 0xfa, 0x50, 0x23, 0xf3, 0x98, 0x8e, 0x90, 0xb6, 0x72, 0x56, 0x62, 0x80, 0x1e, 0xd4,
	0xa5, 0x5e, 0x80, 0x3e, 0x4a, 0x87, 0x56, 0x32, 0x34, 0xae, 0xcf, 0x5b, 0x8e, 0xf1, 0x1e, 0x41,
	0x5d, 0x6a, 0x0a, 0x09, 0xbc, 0x6c, 0xb3, 0xc8, 0x4d, 0xf6, 0x47, 0x74, 0xe2, 0x89, 0x8b, 0x78,
	0x02, 0x21, 0x5b, 0xdc, 0x73, 0x11, 0x0e, 0x60, 0x2d, 0x51, 0xd2, 0xd1, 0x0d, 0xb9, 0x56, 0xe5,
	0x14, 0xfb, 0x5c, 0x94, 0xa7, 0xa0, 0xa6, 0x0b, 0x35, 0xc2, 0xd9, 0x50, 0x2d, 0x82, 0xb5, 0x77,
	0x17, 0xb6, 0x1c, 0x12, 0xb6, 0x82, 0xa9, 0x33, 0x38, 0x0b, 0xcf, 0x2c, 0xb3, 0x65, 0x7a, 0x56,
	0x24, 0xb6, 0xb7, 0x26, 0xca, 0xab, 0xe6, 0xbb, 0xa1, 0x1b, 0x9c, 0x2c, 0xb3, 0x3f, 0x7e, 0x5f,
	0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x46, 0xa3, 0x91, 0xf2, 0x02, 0x14, 0x00, 0x00,
}
