name: CI
on:
  push:
    branches:
      - master
jobs:
  maven:
    name: deploy-maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pull maven
        uses: docker://maven:3.6.0-jdk-8-slim
        with:
          entrypoint: /bin/bash
      - name: Build and Deploy
        env:
          CI_MVN_SETTINGS: ${{ secrets.CI_MVN_SETTINGS }}
        run: |
          mkdir -p /root/.m2
          echo -e "$(echo $CI_MVN_SETTINGS)" > "/root/.m2/settings.xml"
          bash ./systerapb/make-java.sh deploy

  build:
    name: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Google Container Registry
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.STARTAIL_GCP_SERVICE_ACCOUNT }}
        run: docker login -u _json_key -p "$(echo $GCP_SERVICE_ACCOUNT)" gcr.io
      - name: Build Image
        run: docker build . -t gcr.io/startail-io/systera-api:latest
      - name: Push Image
        run: docker push gcr.io/startail-io/systera-api:latest
